Update: test_name_py_2
taro-kuroda-5228/auto_trading_v2 pull request #13
Opened 2021-12-05 11:08 UTC by taro-kuroda-5228

update test_name.py, confirmed it passes pytest.
made __init__.py in ./tests/auto_trading/__init__.py
copied name.py to ./tests/auto_trading/

2021-12-05 11:57 UTC, atsushimemet commented
@taro-kuroda-5228 
#12 のマージ後にレビュー着手させて頂きます。

2021-12-05 21:58 UTC, atsushimemet requested changes
@taro-kuroda-5228 
#12 で行なった変更の後に、今回の変更があったように修正してください。
まず
- tests/auto_trading/__init__.pyは #12 の変更なので今回のPRには含めないでください。
- tests/auto_trading/name.pyは不要ですが、今回のPRに含めた理由を教えてください。
- tests/auto_trading/test_name.py　#12 で行なった変更以外をPRに含めてください。

2021-12-06 11:55 UTC, taro-kuroda-5228 commented
最初pytestを実行したとき、tests/auto_trading/name.pyを入れろという趣旨のエラーが出て、実際に入れたらpassだったので入れていたのですが、改めて実行したら普通にpassだったので消しました！

2021-12-06 11:55 UTC, taro-kuroda-5228 commented
ご確認よろしくお願いします！

2021-12-06 22:18 UTC, atsushimemet approved these changes
+1

2021-12-07 10:31 UTC, merged