Add: test_raw_data.py
taro-kuroda-5228/auto_trading_v2 pull request #15
Opened 2021-12-12 13:39 UTC by taro-kuroda-5228

test_raw_data.pyが完成しました！
pytestはpassしています！

2021-12-12 20:55 UTC, atsushimemet requested changes
@taro-kuroda-5228 
テストコードにもだいぶ慣れてきましたね!大変よく書けてます。
小さな変更がいくつかあるので、そちらの着手のほどよろしくお願い致します!

2021-12-12 20:55 UTC, atsushimemet commented on tests/auto_trading/test_raw_data.py
> +    actual = raw_data_type
@taro-kuroda-5228 
18行と19行はまとめて頂いてOKです。
```
actual = type(RawData(symbol_data).raw_data)
```
理由は右辺の内容から一見して、何をおこなっているかわかるため、変数名に情報を含める必要がないからです。

2021-12-12 20:55 UTC, atsushimemet commented on tests/auto_trading/test_raw_data.py
> +    actual = raw_data_type
ただ、変数名に一度起こしているのはとても良いことだと思います。

2021-12-12 20:55 UTC, atsushimemet commented on tests/auto_trading/test_raw_data.py
> +    actual = data_n
@taro-kuroda-5228 
25行目と26行目もまとめて頂いてOKです。

2021-12-12 20:55 UTC, atsushimemet commented on tests/auto_trading/test_raw_data.py
> +    today = "2021-12-10"
@taro-kuroda-5228 
0番目の値なので、32~33行目でコメントアウトしている記述を使用して、today変数を生成しましょう。
不明点があれば、ご連絡ください。

2021-12-13 12:39 UTC, taro-kuroda-5228 commented
修正しました！

2021-12-13 22:11 UTC, atsushimemet requested changes
@taro-kuroda-5228 
前日の取得方法がとても良かったです!
後少しです。ファイトです!

2021-12-13 22:11 UTC, atsushimemet commented on tests/auto_trading/test_raw_data.py
> +    date_of_week = datetime.date.today().strftime("%A")
@taro-kuroda-5228 
31行目のdatetime.date.today()は30行目で定義したdateを使用すべきです。

2021-12-13 22:11 UTC, atsushimemet commented on tests/auto_trading/test_raw_data.py
> +        date -= datetime.timedelta(days=1)
@taro-kuroda-5228 
前日を取得する関数として切り出しましょう。

2021-12-13 22:11 UTC, atsushimemet commented on tests/auto_trading/test_raw_data.py
> +    expected = pd.DataFrame([symbol_data]).tail(1)[1:6]
@taro-kuroda-5228 
タスクの要求が少し厳密ではなかったかもしれません。
ここでいうindexは、RawDataクラスのraw_data属性のindexであり、すなわち日付です。
この日付の先頭、つまり最新の日付が想定と一致していることを確認して頂ければ、問題ありません。
indexの0番目の行の全ての値を確認する必要はありません。

2021-12-14 10:57 UTC, taro-kuroda-5228 commented
修正させて頂きました！添削お願いします！

2021-12-14 11:07 UTC, atsushimemet approved these changes
+1
大変お疲れ様でした!

2021-12-14 11:10 UTC, merged