Add: test_datamart.py
taro-kuroda-5228/auto_trading_v2 pull request #18
Opened 2021-12-14 11:58 UTC by taro-kuroda-5228

添削お願いします！

2021-12-14 22:46 UTC, atsushimemet requested changes
@taro-kuroda-5228 
少し慣れないかもしれませんが、後少しです!一緒にがんばりましょう!

2021-12-14 22:46 UTC, atsushimemet commented on tests/auto_trading/test_datamart.py
> +    assert all(actual == expected)
@taro-kuroda-5228 
test_datamart_us関数、test_datamart_jp関数では、actual == expectedの結果生成されるpandasのデータフレームの存在を確認しているに過ぎません。

テストを書くとは、行いたいテストを明文化する→テストを実装する、という大きく分けて2つのプロセスがあると考えています。`列が想定通りか`をご自身の中で明文化した上で、テストを作成してください。

2021-12-15 10:17 UTC, taro-kuroda-5228 commented
すいません、愚直で正しいのか分かりませんが、一応passしてます！

2021-12-16 06:27 UTC, atsushimemet requested changes
今週中にテストを書くという概念が体感で理解できるととてもいいです。
短期間なのでなかなか難しいと思いますが(私は1年かかりました。。。情けない 笑)、引き続きしっかりと考えながら頑張っていきましょう!

2021-12-16 06:27 UTC, atsushimemet commented on tests/auto_trading/test_datamart.py
> +    assert all(actual == expected)
@taro-kuroda-5228 
以下の要件を満たすnotebookファイルを生成し、slackの機械学習の実装チャンネルで共有してください!
1. こちらのactualに格納されているデータフレームの先頭5行を表示
2. actual == expectedの結果を表示
3. all(actual == expected)の結果を表示
4. 1~3の内容を踏まえてtest_datamart_usで何をテストしたか日本語で記載

2021-12-18 04:00 UTC, taro-kuroda-5228 commented
列を確認するコードに書き換えました！
ご確認よろしくお願いします！

2021-12-18 05:36 UTC, atsushimemet requested changes
@taro-kuroda-5228 
よく書けてます、お疲れ様でした。
本日の講義で0行目の要素も確認するテスト関数も書くということになってましたので、
そちらも追加してください。

よろしくお願い致します。

2021-12-18 06:39 UTC, taro-kuroda-5228 commented
追加しました！

2021-12-18 09:25 UTC, atsushimemet approved these changes
@taro-kuroda-5228 
大変お疲れ様でした。マージしてください。

2021-12-18 13:19 UTC, merged