Update: model and test_model files
taro-kuroda-5228/auto_trading_v2 pull request #21
Opened 2021-12-20 12:23 UTC by taro-kuroda-5228

2021-12-20 12:24 UTC, taro-kuroda-5228 commented
確認お願いします！

2021-12-20 12:49 UTC, atsushimemet requested changes
@taro-kuroda-5228 
いくつかコメントしております。ご対応お願いします。

2021-12-20 12:49 UTC, atsushimemet commented on tests/auto_trading/test_model.py
> +datamart = Datamart.datamart
@taro-kuroda-5228 
このdatamart変数には、何が格納されてますか?

2021-12-20 12:49 UTC, atsushimemet commented on tests/auto_trading/test_model.py
>  def test_model_class():
@taro-kuroda-5228 
関数名はもう少し考える必要があると思います。

2021-12-20 13:59 UTC, taro-kuroda-5228 commented on tests/auto_trading/test_model.py
> +datamart = Datamart.datamart
すいません！ただのpropertyでした！

2021-12-20 13:59 UTC, taro-kuroda-5228 commented on tests/auto_trading/test_model.py
>  def test_model_class():
修正します！

2021-12-20 14:02 UTC, taro-kuroda-5228 commented
修正しました！ご確認お願いします！

2021-12-21 01:05 UTC, atsushimemet requested changes
1点修正してみましょう!

2021-12-21 01:05 UTC, atsushimemet commented on tests/auto_trading/test_model.py
> +    assert all(model._datamart == datamart)
@taro-kuroda-5228 
2つのデータフレームが等しいかどうかを比較するとき、assert_frame_equalを使用することが多いです。
こちらを使ってみましょう!
参考: [pandas.testing.assert_frame_equal](https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html)

2021-12-22 11:28 UTC, taro-kuroda-5228 commented
修正しました！添削お願いします！

2021-12-22 13:02 UTC, atsushimemet requested changes
1点修正です。お願いします。

2021-12-22 13:02 UTC, atsushimemet commented on tests/auto_trading/test_model.py
> +assert_frame_equal = pandas._testing.assert_frame_equal
@taro-kuroda-5228 
このような書き方はしません。正しくは
```
from pandas.testing import assert_frame_equal
or
from pandas._testing import assert_frame_equal
```
です。修正しましょう。

2021-12-22 13:41 UTC, taro-kuroda-5228 commented
修正しました！添削お願いします！

2021-12-23 12:11 UTC, atsushimemet requested changes
後少しです。頑張りましょう!

2021-12-23 12:11 UTC, atsushimemet commented on tests/auto_trading/test_model.py
> +def test_model_instance__datamart():
@taro-kuroda-5228 
アンダーバー2つはこの関数には不自然です。修正しましょう。
[参考: Descriptive: Naming Styles](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles)

2021-12-23 12:15 UTC, taro-kuroda-5228 commented
修正しました！ご確認お願いします！

2021-12-23 12:19 UTC, atsushimemet approved these changes
+1

2021-12-23 12:32 UTC, merged