Update:model.py and test_model.py
taro-kuroda-5228/auto_trading_v2 pull request #25
Opened 2021-12-25 12:13 UTC by taro-kuroda-5228

ちょっと自信が無いのですが、一応passしています！

2021-12-25 23:48 UTC, atsushimemet requested changes
後少しです!頑張りましょう!

2021-12-25 23:48 UTC, atsushimemet commented on auto_trading/model.py
> +        return self.clf
@taro-kuroda-5228 
fitは以下のように実装しましょう。
```
    def fit(self):
        self.clf = lgb.LGBMClassifier()
        self.clf.fit(self.X, self.y)
```
self.X, self.yに関しては、ご自身で実装してみてください。

2021-12-25 23:48 UTC, atsushimemet commented on tests/auto_trading/test_model.py
> +    assert model.fit(clf) == clf
@taro-kuroda-5228 
test_model_instance_fit_clfの内部を
```
model.fit()
assert model.clf
```
に書き換えましょう。

2021-12-26 01:08 UTC, taro-kuroda-5228 commented
修正しました！添削お願いします！

2021-12-26 05:42 UTC, atsushimemet requested changes
@taro-kuroda-5228 
小さいな修正を一つあげました。よろしくお願いします。

2021-12-26 05:42 UTC, atsushimemet commented on tests/auto_trading/test_model.py
> +clf = lgb.LGBMClassifier()
@taro-kuroda-5228 
使用しないので、この行は削除しましょう。

2021-12-26 05:55 UTC, taro-kuroda-5228 commented
すいません、削除するのを忘れていました💦

2021-12-26 23:27 UTC, atsushimemet requested changes
@taro-kuroda-5228 
1点新しいことを覚えるために修正しましょう!

2021-12-26 23:27 UTC, atsushimemet commented on tests/auto_trading/test_model.py
> +    assert model.clf
@taro-kuroda-5228 
これらの関数は双方ともにtest_model_instanceに関するテストですね。
なので一つのクラスにまとめてしまいましょう。
例としては下記です。

```
class TestModelInstance:
    @pytest.fixture(autouse=True)
    def setup(self):
        self.vending_machine = VendingMachine()
        ticker_msft = Name("MSFT", "US").ticker
        symbol_data_msft = SymbolData(ticker_msft).symbol_data
        raw_data_msft = RawData(symbol_data_msft).raw_data
        datamart = Datamart(raw_data_msft, "open", 5).datamart
        self.model = Model(datamart)

    def test_model_instance_datamart():
        assert_frame_equal(self.model._datamart, datamart)

    def test_model_instance_fit_clf():
        self.model.fit()
        assert self.model.clf
```

2021-12-27 12:43 UTC, taro-kuroda-5228 commented
修正しました！

2021-12-27 22:30 UTC, atsushimemet approved these changes
大変お疲れ様でした!テストにpassしていれば、マージしてください!

2021-12-27 23:03 UTC, merged