Add: auto_trading/datamart_week and month
taro-kuroda-5228/auto_trading_v2 pull request #27
Opened 2022-02-07 07:43 UTC by taro-kuroda-5228

タスク1004の1週間後、1か月後のup/downを予測するためdatamart関連のファイルを2つ追加しました！
修正した点としては、targetをそれぞれ1週間前、1か月前から見たup/downとしております！

2022-02-07 12:30 UTC, atsushimemet requested changes
@taro-kuroda-5228 _target_valueメソッドを除いて同じ記述が繰り返されているので、二つのファイルに分割しない方がいいです。プログラムはdryが原則です。一つのクラスにまとめてみましょう。_target_valueメソッドは引数を加えれば一つにまとめられます。

2022-02-07 12:30 UTC, atsushimemet commented on auto_trading/datamart_month.py
> +    def __init__(self, raw_data, single_values: str, num_lag: int):
@taro-kuroda-5228 raw_data引数のtype hintが漏れてます。

2022-02-07 12:30 UTC, atsushimemet commented on auto_trading/datamart_week.py
> +    def __init__(self, raw_data, single_values: str, num_lag: int):
@taro-kuroda-5228 raw_data引数のtype hintが漏れてます。

2022-02-07 12:44 UTC, taro-kuroda-5228 commented
確かにそうでした！すいません💦

2022-02-07 12:48 UTC, taro-kuroda-5228 commented
datamart.pyにdays_beforeというクラス変数を追加し、_target_valueメソッドに渡しています！

2022-02-08 00:40 UTC, atsushimemet approved these changes
@taro-kuroda-5228 
一度、重複する内容をもつクラスを複数書いて最後にまとめ直す、という作業をしておくと、どこが重複して、どこが重複していないか、が明瞭になってクラスを設計しやすくなると思います。
なので今回はとてもいい機会だったと思います!
お疲れ様でした!

2022-02-08 00:41 UTC, taro-kuroda-5228 commented
ありがとうございます！

2022-02-08 00:41 UTC, merged