Add:feature.py, Update:datamart.py, model.py
taro-kuroda-5228/auto_trading_v2 pull request #29
Opened 2022-02-09 07:57 UTC by taro-kuroda-5228

Modelに渡すべき説明変数をまとめるfeature.pyを追加しました！
またそれに伴って、datamart.py, model.pyにも一部修正を入れております！

・datamart.py
説明変数をまとめたとき、列の値が’close_5’のような形だと、どの説明変数が影響を大きく与えるかなどの解析が面倒になると考え、prefixにtickerを入れた。

・model.py
datamartとfeatureをpd.concatで結合した

2022-02-09 23:49 UTC, atsushimemet requested changes
@taro-kuroda-5228 
いくつかコメントしたところを修正してください!

また、model.pyのl19でslackでお送り頂いたデータマートが生成されているのだと理解しましたが、認識あってますか?

2022-02-09 23:49 UTC, atsushimemet commented on auto_trading/datamart.py
> +    def __init__(self, raw_data, single_values: str, num_lag: int, days_before: int, ticker: str):
raw_data引数のtype hintが抜けてます。

2022-02-09 23:49 UTC, atsushimemet commented on auto_trading/feature.py
> +        self._datamarts = datamarts
@taro-kuroda-5228 
このdatamarts引数にどんな値が入ってくるのか、想像できません。。。docstringに例を記載して頂けますか?

2022-02-09 23:49 UTC, atsushimemet commented on auto_trading/feature.py
> +        self._datamarts = [pd.DataFrame(self._datamart).drop('target', axis=1) for self._datamart in self._datamarts]
@taro-kuroda-5228 
for self._datamartの`self.`がある理由がわからず、、、教えていただけると助かります。

2022-02-10 02:56 UTC, taro-kuroda-5228 commented on auto_trading/feature.py
> +        self._datamarts = [pd.DataFrame(self._datamart).drop('target', axis=1) for self._datamart in self._datamarts]
すいません！なくても行けました！
インスタンス変数だと思い習慣的に入れてしまいました💦

2022-02-10 03:01 UTC, taro-kuroda-5228 commented
修正させて頂きました！
その通りです！分かりにくくて申し訳ありません💦

2022-02-10 12:24 UTC, atsushimemet approved these changes
+1

2022-02-10 12:24 UTC, atsushimemet commented on auto_trading/feature.py
> +        feature = Feature([datamart_DIA, datamart_SPY]).concat_datamarts()
@taro-kuroda-5228 
とてもわかりやすくなりました^^

2022-02-11 00:33 UTC, taro-kuroda-5228 commented
ありがとうございます！

2022-02-11 00:33 UTC, merged